# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

# ✅ Gunakan aturan rekomendasi dari Flutter lints
# The 'flutter_lints' package isn't available in this project; comment out the external include
# If you want to use flutter_lints, add it to dev_dependencies in pubspec.yaml and run `flutter pub get`.
# include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unused_import: ignore  # Abaikan peringatan import tidak terpakai
    unused_field: ignore

linter:
  rules:
    # Tambahkan atau nonaktifkan aturan lint di bawah ini jika diperlukan.
    # Contoh:
    # avoid_print: false          # Nonaktifkan aturan avoid_print
    # prefer_single_quotes: true  # Gunakan kutip tunggal untuk string
